services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
      - keydb
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: my_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge