services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP порт RabbitMQ
      - "15672:15672"     # Веб-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build: ./user_service
    container_name: user_service
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: users
      DB_USER: postgres
      DB_PASSWORD: password
      RABBIT_HOST: rabbitmq

  notification_service:
    build: ./notification_service
    container_name: notification_service
    depends_on:
      - rabbitmq
    restart: always

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    ports:
      - "6379:6379"
    networks:
      - default


volumes:
  pgdata:
